# Generated by Django 3.1.7 on 2021-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('action_required', 'action required'), ('draft', 'draft'), ('sent', 'sent'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='action_required', max_length=15, verbose_name='state')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'ordering': ('-created',),
            },
        ),
    ]
