# Generated by Django 3.1.7 on 2021-03-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='width')),
                ('height', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='height')),
                ('length', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='length')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='weight')),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='retail_price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_products', to='orders.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'saved product',
                'verbose_name_plural': 'saved products',
                'ordering': ('-id',),
            },
        ),
    ]
