# Generated by Django 3.1.7 on 2021-03-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product_savedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='order')),
                ('saved_product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='orders.savedproduct', verbose_name='saved product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ('-id',),
            },
        ),
    ]
